ReaderselfCoreBundle_feed:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/feed.yml"

ReaderselfCoreBundle_item:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/item.yml"

ReaderselfCoreBundle_author:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/author.yml"

ReaderselfCoreBundle_category:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/category.yml"

ReaderselfCoreBundle_member:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/member.yml"

ReaderselfCoreBundle_connection:
    resource: "@ReaderselfCoreBundle/Resources/config/routing/connection.yml"

readerself_api_status:
    path: /status
    defaults:
        _controller: "readerself_core_controller_status:indexAction"
    methods: GET

readerself_api_proxy:
    path: /proxy/{token}
    defaults:
        _controller: "readerself_core_controller_proxy:indexAction"
    methods: GET
