services:
    simplepie:
        class: SimplePie

    #Controller
    readerself_core_controller_abstract:
        class: Readerself\CoreBundle\Controller\AbstractController
        abstract: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
            - [ "setMemberManager", [ "@readerself_core_manager_member" ] ]
            - [ "setActionManager", [ "@readerself_core_manager_action" ] ]
            - [ "setApplicationServerKey", [ %notification_vapid_public_key% ] ]

    readerself_core_controller_content:
        class: Readerself\CoreBundle\Controller\ContentController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_feed:
        class: Readerself\CoreBundle\Controller\FeedController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setAuthorManager", [ "@readerself_core_manager_author" ] ]
            - [ "setCategoryManager", [ "@readerself_core_manager_category" ] ]
            - [ "setCollectionManager", [ "@readerself_core_manager_collection" ] ]
            - [ "setFeedManager", [ "@readerself_core_manager_feed" ] ]

    readerself_core_controller_item:
        class: Readerself\CoreBundle\Controller\ItemController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setAuthorManager", [ "@readerself_core_manager_author" ] ]
            - [ "setCategoryManager", [ "@readerself_core_manager_category" ] ]
            - [ "setFeedManager", [ "@readerself_core_manager_feed" ] ]
            - [ "setItemManager", [ "@readerself_core_manager_item" ] ]

    readerself_core_controller_status:
        class: Readerself\CoreBundle\Controller\StatusController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setSearchManager", [ "@readerself_core_manager_search" ] ]

    readerself_core_controller_proxy:
        class: Readerself\CoreBundle\Controller\ProxyController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_search:
        class: Readerself\CoreBundle\Controller\SearchController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setAuthorManager", [ "@readerself_core_manager_author" ] ]
            - [ "setCategoryManager", [ "@readerself_core_manager_category" ] ]
            - [ "setFeedManager", [ "@readerself_core_manager_feed" ] ]
            - [ "setItemManager", [ "@readerself_core_manager_item" ] ]
            - [ "setSearchManager", [ "@readerself_core_manager_search" ] ]

    readerself_core_controller_category:
        class: Readerself\CoreBundle\Controller\CategoryController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setCategoryManager", [ "@readerself_core_manager_category" ] ]

    readerself_core_controller_author:
        class: Readerself\CoreBundle\Controller\AuthorController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setAuthorManager", [ "@readerself_core_manager_author" ] ]
            - [ "setFeedManager", [ "@readerself_core_manager_feed" ] ]

    readerself_core_controller_push:
        class: Readerself\CoreBundle\Controller\PushController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_connection:
        class: Readerself\CoreBundle\Controller\ConnectionController
        parent: "readerself_core_controller_abstract"

    readerself_core_controller_member:
        class: Readerself\CoreBundle\Controller\MemberController
        parent: "readerself_core_controller_abstract"
        calls:
            - [ "setLdap", [ "%ldap_enabled%", "%ldap_server%", "%ldap_port%", "%ldap_protocol%", "%ldap_rootdn%", "%ldap_rootpw%", "%ldap_basedn%", "%ldap_search_user%", "%ldap_search_group_admin%" ] ]

    #Manager
    readerself_core_manager_abstract:
        class: Readerself\CoreBundle\Manager\AbstractManager
        abstract: true
        calls:
            - [ "setDoctrine", [ "@doctrine" ] ]
            - [ "setEventDispatcher", [ "@event_dispatcher" ] ]
            - [ "setRouter", [ "@router" ] ]

    readerself_core_manager_collection:
        class: Readerself\CoreBundle\Manager\CollectionManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@simplepie"
            - "@readerself_core_manager_member"
        calls:
            - [ "setFacebook", [ "%facebook_enabled%", "%facebook_id%", "%facebook_secret%" ] ]

    readerself_core_manager_migration:
        class: Readerself\CoreBundle\Manager\MigrationManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_search:
        class: Readerself\CoreBundle\Manager\SearchManager
        parent: "readerself_core_manager_abstract"
        public: true
        calls:
            - [ "setElasticsearch", [ "%elasticsearch_enabled%", "%elasticsearch_index%", "%elasticsearch_url%" ] ]

    readerself_core_manager_collection_feed:
        class: Readerself\CoreBundle\Manager\CollectionFeedManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_feed:
        class: Readerself\CoreBundle\Manager\FeedManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_collection_feed"

    readerself_core_manager_item:
        class: Readerself\CoreBundle\Manager\ItemManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_enclosure"

    readerself_core_manager_enclosure:
        class: Readerself\CoreBundle\Manager\EnclosureManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_author:
        class: Readerself\CoreBundle\Manager\AuthorManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_category:
        class: Readerself\CoreBundle\Manager\CategoryManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_item_category"
            - "@readerself_core_manager_feed_category"

    readerself_core_manager_item_category:
        class: Readerself\CoreBundle\Manager\ItemCategoryManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_feed_category:
        class: Readerself\CoreBundle\Manager\FeedCategoryManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_member:
        class: Readerself\CoreBundle\Manager\MemberManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_connection"
            - "@readerself_core_manager_push"

    readerself_core_manager_connection:
        class: Readerself\CoreBundle\Manager\ConnectionManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_push:
        class: Readerself\CoreBundle\Manager\PushManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "%notification_gcm_api_key%"
            - "%notification_vapid_subject%"
            - "%notification_vapid_public_key%"
            - "%notification_vapid_private_key%"

    readerself_core_manager_action:
        class: Readerself\CoreBundle\Manager\ActionManager
        parent: "readerself_core_manager_abstract"
        public: true
        arguments:
            - "@readerself_core_manager_action_item"
            - "@readerself_core_manager_action_item_member"
            - "@readerself_core_manager_action_feed_member"
            - "@readerself_core_manager_action_category_member"

    readerself_core_manager_action_item:
        class: Readerself\CoreBundle\Manager\ActionItemManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action_item_member:
        class: Readerself\CoreBundle\Manager\ActionItemMemberManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action_feed_member:
        class: Readerself\CoreBundle\Manager\ActionFeedMemberManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_action_category_member:
        class: Readerself\CoreBundle\Manager\ActionCategoryMemberManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_digg:
        class: Readerself\CoreBundle\Manager\DiggManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_feedly:
        class: Readerself\CoreBundle\Manager\FeedlyManager
        parent: "readerself_core_manager_abstract"
        public: true

    readerself_core_manager_aol:
        class: Readerself\CoreBundle\Manager\AolManager
        parent: "readerself_core_manager_abstract"
        public: true

    #Listener
    readerself_core_eventlistener_search:
        class: Readerself\CoreBundle\EventListener\SearchListener
        arguments:
            - "@readerself_core_manager_search"
            - "@readerself_core_manager_item"
        tags:
            - { name: "kernel.event_listener", event: "Author.before_remove", method: "removeAuthor" }
            - { name: "kernel.event_listener", event: "Category.before_remove", method: "removeCategory" }
            - { name: "kernel.event_listener", event: "Feed.before_remove", method: "removeFeed" }
            - { name: "kernel.event_listener", event: "Item.before_remove", method: "removeItem" }

    readerself_core_eventlistener_pinboard:
        class: Readerself\CoreBundle\EventListener\PinboardListener
        arguments:
            - "@readerself_core_manager_member"
        tags:
            - { name: "kernel.event_listener", event: "ActionItemMember.after_persist", method: "add" }
            - { name: "kernel.event_listener", event: "ActionItemMember.before_remove", method: "delete" }

    readerself_core_eventlistener_subscribe:
        class: Readerself\CoreBundle\EventListener\SubscribeListener
        arguments:
            - "@readerself_core_manager_member"
        tags:
            - { name: "kernel.event_listener", event: "ActionFeedMember.after_persist", method: "unread" }
