Readerself\CoreBundle\Entity\CollectionFeed:
    repositoryClass: Readerself\CoreBundle\Repository\CollectionFeedRepository
    type: entity
    table: collection_feed
    indexes:
        collection_id:
            columns:
                - collection_id
        feed_id:
            columns:
                - feed_id
    uniqueConstraints:
        collection_id_feed_id:
            columns:
                - collection_id
                - feed_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        error:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        collection:
            targetEntity: Collection
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                collection_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        feed:
            targetEntity: Feed
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                feed_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
    lifecycleCallbacks: {  }
