#crud
readerself_api_feed_create:
    path: /feed
    defaults:
        _controller: "readerself_core_controller_feed:createAction"
    methods: POST

readerself_api_feed_read:
    path: /feed/{id}
    defaults:
        _controller: "readerself_core_controller_feed:readAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_feed_update:
    path: /feed/{id}
    defaults:
        _controller: "readerself_core_controller_feed:updateAction"
    requirements:
        id: '\d+'
    methods: PUT

readerself_api_feed_delete:
    path: /feed/{id}
    defaults:
        _controller: "readerself_core_controller_feed:deleteAction"
    requirements:
        id: '\d+'
    methods: DELETE

#extra
readerself_api_feeds:
    path: /feeds
    defaults:
        _controller: "readerself_core_controller_feed:indexAction"
    methods: GET

readerself_api_feed_action_subscribe:
    path: /feed/action/subscribe/{id}
    defaults:
        _controller: "readerself_core_controller_feed:actionSubscribeAction"
    requirements:
        id: '\d+'
    methods: GET

readerself_api_search_feeds:
    path: /feeds/search
    defaults:
        _controller: "readerself_core_controller_search:feedsAction"
    methods: GET

readerself_api_feeds_import:
    path: /feeds/import
    defaults:
        _controller: "readerself_core_controller_feed:importAction"
    methods: POST

readerself_api_feeds_export:
    path: /feeds/export
    defaults:
        _controller: "readerself_core_controller_feed:exportAction"
    methods: POST
